### ISSUE TITLE
pre-commit hooks for pytest and formatting

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#39]
Add precommit to auto-run `pytest`, format with `black` and run `isort` (`isort` is not running with `black` for some reason?)

some link I found for isort idk how relevant this is, might be for Github action and not pre-commit (add to both anyways)
https://pycqa.github.io/isort/docs/configuration/black_compatibility.html#:~:text=Compatibility%20with%20black&text=All%20that's%20required%20to%20use,isort%20profile%20to%20%22black%22.&text=Beyond%20the%20profile%2C%20it%20is,from%20black's%20default%20of%2088.
```
- repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
```

here's also my `.git/hooks/pre-commit` file for `pytest`
```
#!/usr/bin/env zsh

echo "Running pytest..."
poetry run pytest

# capture exit status
PYTEST_STATUS=$?

exit $PYTEST_STATUS
```
